[package]
name = "test-utils"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[dependencies]
tempfile.workspace = true
chrono.workspace = true
regex.workspace = true

[lib]
path = "src/lib.rs"
